[workspace]
members = [
    "nginx-sys",
    "examples",
]

[package]
name = "ngx"
version = "0.3.0-beta"
edition = "2021"
autoexamples = false
categories = ["api-bindings", "network-programming"]
description = "FFI bindings to NGINX"
repository = "https://github.com/nginxinc/ngx-rust"
homepage = "https://github.com/nginxinc/ngx-rust"
license = "Apache-2.0"
keywords = ["nginx", "module", "sys"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nginx-sys = { path = "nginx-sys", version = "0.1"}

[build-dependencies]
bindgen = "0.64.0"
which = "4.4.0"
duct = "0.13.6"
ureq = { version = "2.6.2", features = ["tls"] }
flate2 = "1.0.25"
tar = "0.4.38"

[badges]
maintenance = { status = "experimental" }
