[package]
name = "nginx-sys"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["staticlib","rlib"]

[dependencies]

[build-dependencies]
bindgen = "0.64.0"
which = "4.4.0"
duct = "0.13.6"
ureq = { version = "2.6.2", features = ["tls"] }
flate2 = "1.0.25"
tar = "0.4.38"
