[package]
name = "nginx-sys"
version = "0.5.0"
edition = "2021"
categories = ["external-ffi-bindings"]
description = "FFI bindings to NGINX"
repository = "https://github.com/nginxinc/ngx-rust"
homepage = "https://github.com/nginxinc/ngx-rust"
license = "Apache-2.0"
keywords = ["nginx", "ffi", "sys"]
build = "build/main.rs"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]

[build-dependencies]
bindgen = "0.70.1"
duct = { version = "0.13.7", optional = true }
flate2 = { version = "1.0.28", optional = true }
tar =  { version = "0.4.40", optional = true }
ureq = { version = "2.9.6", features = ["tls"], optional = true }
which = { version = "6.0.0", optional = true }

[features]
vendored = ["dep:which", "dep:duct", "dep:ureq", "dep:flate2", "dep:tar"]
