#
# https://stackoverflow.com/questions/28124221/error-linking-with-cc-failed-exit-code-1
#
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
