name: License Scanning

on:
  - push

jobs:
  fossa:
    # This job is only useful when run on upstream
    if: github.repository == 'nginx/ngx-rust' || github.event_name == 'workflow_dispatch'
    name: FOSSA scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run FOSSA scan and upload build data
        uses: fossas/fossa-action@c414b9ad82eaad041e47a7cf62a4f02411f427a0 # v1.8.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
