name: sanitizers

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CARGO_INCREMENTAL: '0'
  CARGO_TERM_COLOR: 'always'
  RUST_BACKTRACE: '1'
  NGINX_SOURCE_DIR: nginx
  NGINX_EXTRA_CONFIGURE_ARGS: --with-http_v3_module
  BUILDREQUIRES: >-
    openssl-devel pcre2-devel zlib-devel
    cargo rust-src rustfmt
    clang compiler-rt llvm
    git-core
    make patch which
    perl-FindBin
    perl-IO-Socket-INET6
    perl-IO-Socket-SSL
    perl-Test-Harness
    perl-Test-Simple
    perl-lib

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/almalinux/almalinux:10

    strategy:
      fail-fast: false
      matrix:
        nginx-ref:
          # master
          - stable-1.30

    steps:
      - name: Install dependencies
        run:  dnf install -y ${BUILDREQUIRES}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ matrix.nginx-ref }}
          repository: 'nginx/nginx'
          path: 'nginx'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: 'nginx/nginx-tests'
          path: 'nginx/tests'

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            objs-*/**/CACHEDIR.TAG
            objs-*/**/ngx-debug
            objs-*/**/ngx-release
          key: ${{ runner.os }}-cargo-asan-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-asan-

      - name: Configure and build nginx
        run: |
          patch -d "$NGINX_SOURCE_DIR" -p1 < $GITHUB_WORKSPACE/build/nginx-sanitizer-support.patch
          make -j$(nproc) BUILD=sanitize build

      - name: Run tests
        env:
          # `container` job steps are running as root, and thus all the files
          # created by the test scripts are owned by root.
          # But the worker processes are spawned as "nobody" by default,
          # resulting in permission errors.
          TEST_NGINX_GLOBALS: >-
              user root;
        run: |
          make -j$(nproc) BUILD=sanitize TEST_PREREQ= test
