name: Unix

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
  pull_request:

permissions: {}

env:
  CARGO_INCREMENTAL: '0'
  CARGO_TERM_COLOR: 'always'
  RUST_BACKTRACE: '1'
  NGX_CONFIGURE_CMD: >-
    auto/configure
    --with-compat
    --with-debug
    --with-http_realip_module
    --with-http_ssl_module
    --with-http_v2_module
    --with-stream
    --with-stream_realip_module
    --with-stream_ssl_module
    --with-threads

  NGX_CONFIGURE_DYNAMIC_MODULES: >-
    --add-dynamic-module=${{ github.workspace }}/examples
  NGX_CONFIGURE_STATIC_MODULES: >-
    --add-module=${{ github.workspace }}/examples

  NGX_TEST_FILES: examples/t
  NGX_TEST_GLOBALS_DYNAMIC: >-
    load_module ${{ github.workspace }}/nginx/objs/ngx_http_async_module.so;
    load_module ${{ github.workspace }}/nginx/objs/ngx_http_awssigv4_module.so;
    load_module ${{ github.workspace }}/nginx/objs/ngx_http_curl_module.so;
    load_module ${{ github.workspace }}/nginx/objs/ngx_http_shared_dict_module.so;
    load_module ${{ github.workspace }}/nginx/objs/ngx_http_upstream_custom_module.so;

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nginx-ref:
          - master
          - stable-1.30
        module:
          - static
          - dynamic
        include:
          # minimal supported nginx version (Debian bookworm: 1.22.1)
          - nginx-ref: stable-1.22
            module: dynamic

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ matrix.nginx-ref }}
          repository: 'nginx/nginx'
          path: 'nginx'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: 'nginx/nginx-tests'
          path: 'nginx/tests'
          sparse-checkout: |
            lib

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            nginx/objs/**/CACHEDIR.TAG
            nginx/objs/**/ngx-debug
            nginx/objs/**/ngx-release
          key: ${{ runner.os }}-nginx-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-nginx-

      - name: set up Rust toolchain
        run: rustup toolchain install --no-self-update --override --profile minimal stable

      - name: Update configure arguments
        if: matrix.nginx-ref != 'stable-1.22'
        run: |
            echo NGX_CONFIGURE_CMD="${NGX_CONFIGURE_CMD} --with-http_v3_module" \
                >> "$GITHUB_ENV"

      - name: Configure nginx with static modules
        if: matrix.module == 'static'
        working-directory: nginx
        run: |
          ${NGX_CONFIGURE_CMD} \
              ${NGX_CONFIGURE_STATIC_MODULES}

      - name: Configure nginx with dynamic modules
        if: matrix.module != 'static'
        working-directory: nginx
        run: |
          ${NGX_CONFIGURE_CMD} \
              ${NGX_CONFIGURE_DYNAMIC_MODULES}
          echo TEST_NGINX_GLOBALS="$NGX_TEST_GLOBALS_DYNAMIC" >> "$GITHUB_ENV"

      - name: Build nginx
        working-directory: nginx
        run: make -j$(nproc)

      - name: Run tests
        env:
          PERL5LIB: ${{ github.workspace }}/nginx/tests/lib
          TEST_NGINX_BINARY: ${{ github.workspace }}/nginx/objs/nginx
          TEST_NGINX_MODULES: ${{ github.workspace }}/nginx/objs
          TEST_NGINX_VERBOSE: 1
        run: |
          prove -j$(nproc) --state=save ${NGX_TEST_FILES} || prove -v --state=failed
