name: Unix

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CARGO_INCREMENTAL: '0'
  CARGO_TERM_COLOR: 'always'
  RUST_BACKTRACE: '1'
  NGINX_SOURCE_DIR: nginx

jobs:
  rust-version:
    name: Minimal supported Rust version
    outputs:
      version: ${{ steps.read_version.outputs.msrv }}
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: read_version
        run: |
          awk -F '=' \
            '/^rust-version[[:space:]]*=/ { gsub(/([" ]|#.*)/,"",$2); print ("msrv=" $2) }' \
            Cargo.toml \
          | tee -a "$GITHUB_OUTPUT"

  test:
    needs: rust-version

    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
        rust-version:
          - stable
        nginx-ref:
          - master
          - stable-1.30
        build:
          - debug
          - debug-static

        include:
          # minimal supported nginx version (Debian bookworm: 1.22.1)
          - runner: ubuntu-latest
            rust-version: stable
            nginx-ref: stable-1.22
            build: debug

          # minimal supported Rust version
          - runner: ubuntu-latest
            rust-version: ${{ needs.rust-version.outputs.version }}
            nginx-ref: stable-1.30
            build: debug

          # macOS
          - runner: macos-latest
            rust-version: stable
            nginx-ref: stable-1.30
            build: debug

    env:
      NGINX_EXTRA_CONFIGURE_ARGS: >-
        ${{ matrix.nginx-ref != 'stable-1.22' && '--with-http_v3_module' || '' }}

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ matrix.nginx-ref }}
          repository: 'nginx/nginx'
          path: 'nginx'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: 'nginx/nginx-tests'
          path: 'nginx/tests'
          sparse-checkout: |
            lib

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            objs-*/**/CACHEDIR.TAG
            objs-*/**/ngx-debug
            objs-*/**/ngx-release
            target/
          key: ${{ runner.os }}-nginx-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-nginx-

      - name: set up Rust toolchain
        env:
          toolchain: ${{ matrix.rust-version }}
        run: |
          rustup toolchain install --no-self-update --override --profile minimal \
            --component 'rustfmt,clippy' $toolchain

      - name: CPU count
        run: echo PARALLEL="-j $(getconf _NPROCESSORS_ONLN)" >> "$GITHUB_ENV"

      - name: build
        id: build
        run: make BUILD=${{ matrix.build }} $PARALLEL build

      - name: check
        # always run if build succeeds
        if: ${{ !cancelled() && steps.build.outcome == 'success' }}
        run: make BUILD=${{ matrix.build }} check

      - name: run tests
        # always run if build succeeds
        if: ${{ !cancelled() && steps.build.outcome == 'success' }}
        run: make BUILD=${{ matrix.build }} TEST_PREREQ= test

      - name: run unittests
        # always run if build succeeds
        if: ${{ !cancelled() && steps.build.outcome == 'success' }}
        run: make BUILD=${{ matrix.build }} $PARALLEL unittest
