name: Windows

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CARGO_INCREMENTAL: '0'
  CARGO_TERM_COLOR: 'always'
  RUST_BACKTRACE: '1'
  NGX_CONFIGURE_CMD: >-
    auto/configure
    --with-cc=cl
    --with-compat
    --with-debug
    --prefix=
    --conf-path=conf/nginx.conf
    --pid-path=logs/nginx.pid
    --http-log-path=logs/access.log
    --error-log-path=logs/error.log
    --sbin-path=nginx.exe
    --http-client-body-temp-path=temp/client_body_temp
    --http-proxy-temp-path=temp/proxy_temp
    --http-fastcgi-temp-path=temp/fastcgi_temp
    --http-scgi-temp-path=temp/scgi_temp
    --http-uwsgi-temp-path=temp/uwsgi_temp
    --with-cc-opt=-DFD_SETSIZE=1024
    --with-pcre=objs/lib/pcre
    --with-zlib=objs/lib/zlib
    --with-http_v2_module
    --with-http_realip_module
    --with-mail
    --with-stream
    --with-stream_realip_module
    --with-openssl=objs/lib/openssl
    --with-openssl-opt="no-asm no-module no-tests no-makedepend -D_WIN32_WINNT=0x0601"
    --with-http_ssl_module
    --with-mail_ssl_module
    --with-stream_ssl_module
    --add-module=${{ github.workspace }}/examples

  NGX_TEST_FILES: examples/t

jobs:
  test:
    runs-on: windows-2022
    env:
      TEMP: "C:\\TEMP"
      TMP: "C:\\TEMP"
      TMPDIR: "C:\\TEMP"
      VCARCH: x64

    strategy:
      fail-fast: false
      matrix:
        nginx-ref:
          - master

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ matrix.nginx-ref }}
          repository: 'nginx/nginx'
          path: 'nginx'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: 'nginx/nginx-tests'
          path: 'nginx/tests'
          sparse-checkout: |
            lib

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            nginx/objs/**/CACHEDIR.TAG
            nginx/objs/**/ngx-debug
            nginx/objs/**/ngx-release
          key: ${{ runner.os }}-nginx-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-nginx-

      - name: set up Rust toolchain
        run: rustup toolchain install --no-self-update --override --profile minimal stable

      - name: Prepare build environment
        shell: bash
        working-directory: nginx
        run: |
          print_var() {
            gmake -f misc/GNUmakefile --eval="print_$1: ; @echo \$($1)" "print_$1"
          }

          OPENSSL_VERSION=$(print_var OPENSSL | cut -d- -f2-)
          PCRE2_VERSION=$(print_var PCRE | cut -d- -f2-)
          ZLIB_VERSION=$(print_var ZLIB | cut -d- -f2-)

          # Disable dynamic lookup of WSAPoll(); it crashes if the symbol is already imported by
          # Rust stdlib.
          sed 's/\(_WIN32_WINNT\s*\) 0x0501/\1 0x0601/' -i src/os/win32/ngx_win32_config.h

          echo VCVARSALL="$('C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' -products \* -latest -property installationPath)\\VC\\Auxiliary\\Build\\vcvarsall.bat" \
              >> "$GITHUB_ENV"

          mkdir -p $TEMP
          mkdir -p objs/lib

          curl -fsLO https://github.com/PCRE2Project/pcre2/releases/download/pcre2-$PCRE2_VERSION/pcre2-$PCRE2_VERSION.tar.gz
          tar -C objs/lib --transform "s/pcre2-$PCRE2_VERSION/pcre/" -xzf ./pcre2-$PCRE2_VERSION.tar.gz
          echo '#include <stdint.h>' > objs/lib/pcre/src/inttypes.h

          curl -fsLO https://github.com/madler/zlib/releases/download/v$ZLIB_VERSION/zlib-$ZLIB_VERSION.tar.gz
          tar -C objs/lib --transform "s/zlib-$ZLIB_VERSION/zlib/" -xzf ./zlib-$ZLIB_VERSION.tar.gz

          curl -fsLO https://github.com/openssl/openssl/releases/download/openssl-$OPENSSL_VERSION/openssl-$OPENSSL_VERSION.tar.gz
          tar -C objs/lib --transform "s/openssl-$OPENSSL_VERSION/openssl/" -xzf ./openssl-$OPENSSL_VERSION.tar.gz

      - name: Configure and build nginx
        shell: cmd
        working-directory: nginx
        run: |
          @echo on
          call "%VCVARSALL%" %VCARCH%
          bash.exe %NGX_CONFIGURE_CMD%
          nmake -f objs/Makefile

      - name: Run tests
        shell: cmd
        env:
          PERL5LIB: "${{ github.workspace }}\\nginx\\tests\\lib"
          TEST_NGINX_BINARY: "${{ github.workspace }}\\nginx\\objs\\nginx.exe"
          TEST_NGINX_VERBOSE: 1
        run: |
          prove --state=save %NGX_TEST_FILES% || prove -v --state=failed
